### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by williamxu7** [resplab/ISARIC4C#1]
- [ ] Update README
- [ ] Create PRISM repository
- [ ] Test inputs and outputs on server
- [ ] Develop Excel VBA user-interface
